CREATE DATABASE HOTEL_MANAGEMENT;
SHOW DATABASES;
USE HOTEL_MANAGEMENT;
CREATE TABLE DETAILS(
ID INT,
CUSTAMER_NAME VARCHAR(50),
FOOD VARCHAR(100) UNIQUE,
QUANTITY INT,
PRICE INT,
ORDER_DATE DATE);



INSERT INTO DETAILS(ID,CUSTAMER_NAME,FOOD,QUANTITY,PRICE,ORDER_DATE)
VALUES(1,'AMIT','PIZZA',2,500,'2026-03-12');

USE HOTEL_MANAGEMENT;

INSERT INTO DETAILS(ID,CUSTAMER_NAME,FOOD,QUANTITY,PRICE,ORDER_DATE)
VALUES(2,'PRIYA','BURGER',2,150,'2026-04-01');

USE HOTEL_MANAGEMENT;
INSERT INTO DETAILS(ID,CUSTAMER_NAME,FOOD,QUANTITY,PRICE,ORDER_DATE)
VALUES(3,'RAHUL','PASTA',3,300,'2026-04-01'),
(4,'NEHA','SANDWICH',2,200,'2026-04-02'),
(5,'SURESH','BRIYANI',1,250,'2026-04-02');

SELECT*FROM DETAILS;

