CREATE DATABASE HOTEL;
SHOW DATABASES;
USE HOTEL;
CREATE TABLE FOOD_INFO(
HOTEL_NAME VARCHAR(50),
MOBILE INT,
FOOD VARCHAR(50),
time int);
SELECT*FROM FOOD_INFO;

INSERT INTO FOOD_INFO(HOTEL_NAME,MOBILE,FOOD,TIME)
  VALUES('RAJAFOODS',900363,'DOSA',67);
 
 SELECT*FROM FOOD_INFO;



