CREATE DATABASE STUDENTS_DB;
SHOW DATABASES;
USE STUDENTS_DB;
CREATE TABLE STUDENT(
    STU_ID INT PRIMARY KEY,
    NAME VARCHAR(80),
    AGE INT,
    COURSE VARCHAR(50)
);

CREATE TABLE MARKS(
    MARK_ID INT PRIMARY KEY,
    STUDENT_ID INT,
    SUBJECT VARCHAR(100),
    MARKS INT,
    FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(STU_ID)
);

INSERT INTO STUDENT VALUES
(1, 'MEYKANDAN', 19, 'B.SC.CS [AIML]');
INSERT INTO STUDENT VALUES (2,'RANGA',21,'AIML'),
(3,'PARTHI',19,'AIML');
INSERT INTO STUDENT VALUES(4,'BHART',19,'AIML');
INSERT INTO MARKS VALUES
(101, 1, 'Maths', 95);
INSERT INTO MARKS VALUES
(102,2,'MATHS',100),
(103,3,'MATHS',100);

SELECT STUDENT.NAME,MARKS.SUBJECT,MARKS.MARKS
FROM STUDENT
LEFT JOIN MARKS
ON STUDENT.STU_ID = MARKS.STUDENT_ID;

SELECT STUDENT.NAME,MARKS.SUBJECT
FROM STUDENT
CROSS JOIN MARKS



