SHOW DATABASES;
CREATE DATABASE STUDENT;
SHOW DATABASES;
USE STUDENT;
CREATE table STUDENT_INFO(
STU_ID INT,
NAME varchar(40),
AGE INT,
GENDER varchar(20),
EMAIL VARCHAR(50),
COURSE VARCHAR(20),
ADMISSION_DATE DATE);
select*FROM STUDENT_INFO;

INSERT INTO STUDENT_INFO(STU_ID,NAME,AGE,GENDER,EMAIL,COURSE,ADMISSION_DATE)
values(1,'RAHUL',22,'MALE','RAGUL@GMAIL.COM','B SC CS [AIML]','2024-09-03');

SELECT*FROM STUDENT_INFO;

UPDATE STUDENT_INFO
SET COURSE = 'MCA FINAL YEAR'
STUDENT_ID = 1;
